SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 768

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 45
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 400

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

# UFO settings
UFO_RADIUS = 30
UFO_SPEED = 150
UFO_MIN_SPAWN_TIME = 10   # seconds
UFO_MAX_SPAWN_TIME = 30   # seconds
